---
apiVersion: v1
kind: Namespace
metadata:
  name: chaos-sandbox

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: chaos-sandbox
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 4
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: chaos-sandbox
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80